/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:ed283f82-fb0a-41ee-84d7-dca8820e0a57",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_qeahrg7XF",
    "aws_user_pools_web_client_id": "7r8ri9h8k2d4epfkps9ab3kfvi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kcqmcauwyfdlnmkqxcj7576uny.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bopampe3ibdcdkz2syriyehpt4"
};


export default awsmobile;
